version: '3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - '5432'
    env_file:
      - ./.env

  backend:
    image: dkr3d3/backend:v1.09.2022
    restart: always
    volumes:
        - static_value:/app/static/
        - media_value:/app/media/
    depends_on:
        - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value: