# Generated by Django 2.2.16 on 2022-08-27 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220824_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredients',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='Добавьте ингредиент')], verbose_name='Количество ингредиента в выбранных единицах'),
        ),
    ]
