# Generated by Django 2.2.16 on 2022-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220827_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredients',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
