# Generated by Django 2.2.16 on 2022-08-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220827_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('id',), 'verbose_name': 'Ингредиент'},
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.Ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.Recipes', verbose_name='Рецепт'),
        ),
    ]
