# Generated by Django 2.2.16 on 2022-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220827_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#E26C2D', 'ORANGE'), ('#49B64E', 'GREEN'), ('#8775D2', 'PURPLE')], max_length=10, verbose_name='Цветовой HEX-код'),
        ),
    ]
