# Generated by Django 2.2.16 on 2022-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220828_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('ORANGE', '#E26C2D'), ('GREEN', '#49B64E'), ('PURPLE', '#8775D2')], max_length=10, verbose_name='Цветовой HEX-код'),
        ),
    ]
