# Generated by Django 2.2.16 on 2022-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220828_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#E26C2D', '#E26C2D'), ('#49B64E', '#49B64E'), ('#8775D2', '#8775D2')], max_length=10, verbose_name='Цветовой HEX-код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин')], max_length=100, verbose_name='Название тега'),
        ),
    ]
