# Generated by Django 2.2.16 on 2022-08-31 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220831_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredients',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Добавьте количество ингредиента')], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorites'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shoppingcart'),
        ),
    ]
