# Generated by Django 3.2.13 on 2022-09-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20220901_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='tag',
            new_name='tags',
        ),
    ]
