# Generated by Django 2.2.16 on 2022-08-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscribing',
            new_name='is_subscribed',
        ),
    ]
