# Generated by Django 3.2.13 on 2022-09-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesingredients',
            old_name='count',
            new_name='amount',
        ),
    ]
